name: GH-bot

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: github.event.issue.pull_request != null && "${{ startsWith(github.event.comment.body, '/hey bot') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get branch name
        id: branch
        run: |
          branchName=$(gh pr view ${{ github.event.issue.number }} --json headRefName --jq '.headRefName')
          echo $branchName
          echo "branchName=$branchName" >> $GITHUB_OUTPUT

      - name: Latest Job Id of this Pull Request
        id: job
        run: |
          jobId=$(gh run list -b ${{ steps.branch.outputs.branchName }} -w "CI" --json databaseId --jq '.[0].databaseId')
          echo $jobId
          echo "jobId=$jobId" >> $GITHUB_OUTPUT

      - name: comment on PR
        run: |
          gh pr comment ${{ github.event.issue.number }} -b "Hello, I'm a bot.
          The latest job id is ${{ steps.job.outputs.jobId }}"

